### ISSUE TITLE
The ability to compile .inc files

### ISSUE THREAD

**Issue by NexiusTailer** [dennorske/atom-pawn-build#4]
Do I have the way to configure this to compile .inc files at the moment?
If not, this would be a good update to add it.

**Comment by dennorske** [comment]
@NexiusTailer Sorry, I haven't seen there has been issues posted here.

Of course!
Will keep developing this, will make .inc files compatible.

**Comment by dennorske** [comment]
Fixed in 5da0916f33b6c5663ad6f4b4166b7adc3e9fa1f1
Thanks for filing this.

den
