### ISSUE TITLE
Nothing happens by pressing F5, what's the problem?

### ISSUE THREAD

**Issue by ProDexortie** [dennorske/atom-pawn-build#6]
Pawn-build is installed, compiler directory is right
![image](https://user-images.githubusercontent.com/56790078/67164081-2b0a4400-f37f-11e9-99a4-43120ec73f3d.png)

**Comment by dennorske** [comment]
Hi!

I'll make sure to update the package. It has some broken dependencies causing it not to work.

**Comment by dennorske** [comment]
Fixed in #8 

![image](https://user-images.githubusercontent.com/3287543/68998970-7a2d9100-08b9-11ea-81f2-4bc26a7a40b8.png)

Enjoy!
